In [45]:
import pandas as pd
ai=pd.read_csv("/content/AssetIdentity.txt", sep="|")
ai.head()

,S2ID,Name,Instrument,IssuerID,ISOCountryCode,ISOCurrencyCode,RootID,StartDate,EndDate
0,ARGAAA1,ACINDAR,STOCK,A29652,ARG,ARS,ARGAAA1,19961231,20090323
1,ARGAAA2,ACINDAR IND. (CLASS'A',STOCK,A29652,ARG,ARS,ARGAAA2,19970918,20090323
2,ARGAAB1,ALPARGATAS,STOCK,A05344,ARG,ARS,ARGAAB1,19961231,20140107
3,ARGAAC1,ALUAR ALUMINIO ARGENTI,STOCK,A05422,ARG,ARS,ARGAAC1,19961231,20010729
4,ARGAAC1,ALUAR ALUMINIO ARG,STOCK,A05422,ARG,ARS,ARGAAC1,20010730,20020508

In [46]:
im=pd.read_csv("/content/IDMapping.txt", sep="|")
im.head()
im.value_counts()

S2ID     AssetIDType  AssetID       StartDate  EndDate
ARGAAA1  CINS         P00879117     19961231   20090323    1
CANIHI1  SEDOL        2623687       20000825   20080213    1
         ISIN         CA8772561079  20000825   20080213    1
         CUSIP        877256107     20000825   20080213    1
                      876944109     19990112   20000824    1
                                                          ..
CAN1481  CUSIP        771182201     20041001   20100216    1
         CINS         771182201     20041001   20100216    1
CAN1471  SEDOL        B14ZGV0       20060817   20751231    1
         LOCALID      CAAZ          20060818   20751231    1
POLAGO1  LOCALID      PLMNI         20100927   20751231    1
Length: 125210, dtype: int64

In [56]:
def find_well_known_ids(root_id, date):
    active_ids = set()
    filtered_data = im[(im["StartDate"] <= date) & (im["EndDate"] >= date)]
    for index, row in filtered_data.iterrows():
        if row["S2ID"] in root_id_to_s2id[root_id]:
            active_ids.add(row["WellKnownID"])
    return list(active_ids)

In [57]:
root_id_to_s2id = ai.groupby("RootID")["S2ID"].apply(list).to_dict()

In [61]:
well_known_id_type = input("Choose between Sedol/Cusip/ISIN: ")
root_id = input("Enter RootID: ")
# root_id=int(root_id)
date = input("Enter date in YYYYMMDD format: ")
# date=str(date)
# date=int(date)

Choose between Sedol/Cusip/ISIN: ISIN
Enter RootID: ARGAAA1
Enter date in YYYYMMDD format: 20230918

In [62]:
active_well_known_ids = find_well_known_ids(root_id, date)

TypeError: ignored

In [ ]:
print(",".join(active_well_known_ids))